direction: right
index: index.js
# index2: index.js

recreateTable: recreateTable
sortByKey: sortByKey
setSorting: setSorting
setPaginationNum: setPaginationNum
setPaginationPage: setPaginationPage
red: red
redirectToLoginPage: redirectToLoginPage
createAuthorOptionMenu: createAuthorOptionMenu
createDepartmentsOptionMenu: createDepartmentsOptionMenu
resetTable: resetTable
createPaginationRow: createPaginationRow
createTable: createTable
addBox: addBox
submitAddRow: submitAddRow
onUpdateClick: onUpdateClick
deleteTableRow: deleteTableRow
getDocuments: getDocuments
getAuthors: getAuthors
getDepartments: getDepartments
onStartup: onStartup 

index -> recreateTable
index -> sortByKey
index -> setSorting
index -> setPaginationNum
index -> setPaginationPage
index -> red
index -> redirectToLoginPage
index -> createAuthorOptionMenu
index -> createDepartmentsOptionMenu
index -> resetTable
index -> createPaginationRow
index -> createTable
index -> addBox
index -> submitAddRow
index -> onUpdateClick
index -> deleteTableRow
index -> getDocuments
index -> getAuthors
index -> getDepartments
index -> onStartup
