api: "api.hy"
ra: run-api
rn: "run.hy"

rn -> main
api -> ra


mod: "models.hy"

sk: "Class: SortKey"
doc: "Class: Document"
au: "Class: Author"
dep: "Class: Department"
usr: "Class: User"

mod -> sk
mod -> doc
mod -> au
mod -> dep
mod -> usr

