direction: right

f: "Функции ПС"

gui: "Создание графических элементов" {
  width: 300
}

db: "Работа с БД" {
  width: 300
}
gdb: "Получение данных из БД"
udb: "Обновление данных в БД"
ddb: "Удаление данных из БД"
db -> gdb
db -> udb
db -> ddb

au: "Авторизация" {
  width: 300
}
lg: "Вход в систему"
lgo: "Выход из системы"
au -> lg
au -> lgo

clapi: "Функции обращения к REST API" {
  width: 300
}
gin: "Получение данных с сервера"
uin: "Обновление данных на сервере"
din: "Удаление данных на сервере"
clapi -> gin
clapi -> uin
clapi -> din

inf: "Информационные" {
  width: 300
}
spr: "Получение справочной информации"
ain: "Получение информации об авторе"
inf -> spr
inf -> ain


f -> db
f -> au
f -> gui
f -> clapi
f -> inf
